steps:
  # Step 1: Build the Go application  
  - name: 'golang:1.21'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd appengine/api
        go mod tidy
        go build -v .
    env:
      - 'GO111MODULE=on'
      - 'CGO_ENABLED=0'
      - 'GOOS=linux'

  # Step 2: Deploy to App Engine
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd appengine/api
        gcloud app deploy app.yaml --quiet --project=${PROJECT_ID}

# Build options
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

# Substitutions for variables
substitutions:
  _SERVICE_NAME: 'api'

timeout: '1200s'
